### ISSUE TITLE
softRevalidate error when no fetcher or default fetcher provided.

### ISSUE THREAD

**Issue by rostero1** [zeit/swr#123]
I'm trying to use swr to read in a value without a fetcher, since I know the fetch was started elsewhere (tab one).

Using the [provided demo](https://codesandbox.io/s/eager-field-zs7v8), tab between _one_ and _three_.  Eventually you'll see the following error:

```
index.js:1375 Result Error TypeError: fn is not a function
    at use-swr.js:213
    at softRevalidate (use-swr.js:321)
```

**Comment by quietshu** [comment]
Because currently a `fetcher` is always required by SWR, either you provide it via the `options` param, or pass it to the `SWRConfig` context. 

But we plan to support this feature, so SWR can handle the case that no fetcher is provided (e.g.: just read from the cache). 

With #106 (cc @aequasi), so things like #76 can be much simpler:
```
useSWR('key', { initialData })
```
