### ISSUE TITLE
[React Native] Can't find variable: __dirname

### ISSUE THREAD

**Issue by hiromitz** [zeit/swr#137]
I simply added
```
import useSWR from 'swr'
```
then error occurred Can't find variable: __dirname
```__dirname``` is on compiled dist code, but React Native doesn't support ```_dirname```.

**Comment by gponsinet** [comment]
The `__dirname` variable is located in `node_modules/swr/dist/index.js`
I need to import `swr/esm` to bypass it

**Comment by n3tr** [comment]
@quietshu I can help take a look on this one :)

**Comment by mohmdalfaha** [comment]
I am facing a similar issue but when importing it from ```import useSWR from '@zeit/swr'``` it works fine @n3tr  Thanks for maintaining this. Do you have any React native example. Because I am facing a hard time getting the cached data when the device is offline. 

I am expecting this library to serve the most recent cached api response and when online it revalidates and bring the recent response. Does is it work this way or I am missing something. Thanks again @n3tr .

**Comment by n3tr** [comment]
@mohmdalfaha doesn't it return a cached data when device is offine? 🤔 

I only use `swr` in my hobby project and haven't thought about the online/offline thing 😅 . 

I will help take a look when I have time. My idea is just creating custom fetch hook, observing [`netinfo`](https://github.com/react-native-community/react-native-netinfo) event  ,and revalidate if needed.

**Comment by quietshu** [comment]
The current cache structure needs some refactoring to support async cache mechanisms. And after that,  we will be able to support custom cache APIs like AsyncStorage.

**Comment by ramisalem** [comment]
@quietshu  I really liked the amazing hook you built,  Although I am wondering if it supports offline mode, I have tried it with offline mode but it did not work
