### ISSUE TITLE
TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by tmaiaroto** [zeit/swr#146]
Following examples for passing additional values to the fetcher, it describes using an array of values. It doesn't indicate that they should be an array of objects. Should they? It's a bit awkward if so. However, if using primitive types I sometimes notice a type error because WeakMap keys should be Object.

https://github.com/zeit/swr/blob/987bbb2e82f3454e7a0f5f264e9f2909278844a5/src/libs/hash.ts#L20

Is this correct? Would it be correct to check the type of `args[i]` in this recent change and convert the value to an Object to be used for the key instead?

**Comment by tmaiaroto** [comment]
I gave it an array of objects and that may now have led to a "Maximum update depth exceeded" error. I'm not really sure how to avoid this type error now.

**Comment by tmaiaroto** [comment]
It may have been because one of the values in the array I passed was undefined (it was an auth token I needed to make the request, so if not logged in and the hook fired). I made it fallback to have an empty string if undefined. Might be nice to check for this or throw some error that helps pinpoint it.

**Comment by quietshu** [comment]
You can pass both primitive types (notice [here](https://github.com/zeit/swr/blob/987bbb2e82f3454e7a0f5f264e9f2909278844a5/src/libs/hash.ts#L15-L17)) and objects. I think the reason that you got "Maximum update depth exceeded" is because you're passing different objects on every render. For example `useSWR([{}])` will be considered to be a new object every time. You need to use `useMemo` or something to make it stable. 

> Might be nice to check for this and just automatically make undefined an empty string or throw some error that helps pinpoint it.
Yeah that's a good suggestion, thank you :+1:

**Comment by pacocoursey** [comment]
The documentation has been updated to mention that your keys should be stable.

https://github.com/zeit/swr#multiple-arguments

Additionally, the following falsy values will behave the following way when used as a key:
```
      // "undefined" -> '"undefined"'
      // undefined   -> 'undefined'
      // 123         -> '123'
      // null        -> 'null'
      // "null"      -> '"null"'
```
