### ISSUE TITLE
Is it possible to handle 429 server error

### ISSUE THREAD

**Issue by muhaimincs** [zeit/swr#233]

**Comment by sergiodxa** [comment]
You need to do that in your fetcher and throw and error.

**Comment by muhaimincs** [comment]
here is my fetcher
```js
export default async function fetcher(...args) {
  try {
    const res = await fetch(...args);
    return res.json();
  } catch (err) {
    console.log(err);
    throw err;
  }
}
```

**Comment by muhaimincs** [comment]
@sergiodxa can help?

**Comment by sergiodxa** [comment]
This is what I do in my fetcher.

```js
if (response.status >= 400 && response.status <= 499) {
  throw new ClientError('API Client Error', await response.json());
}
```
ClientError is a custom error class I made extending Error, it has the message `API Client Error` to easily check if it's an error and the data received by the server.

I do that just below the fetch, I don't check if it's a 200 because there are other 2xx status codes that are not errors, only check for 204 since it should not have content so I return `undefined` instead of running `response.json()`.
