### ISSUE TITLE
refreshInterval question

### ISSUE THREAD

**Issue by AjaxSolutions** [zeit/swr#241]
What will happen when refreshInterval is set to refresh frequently and the previous request is still pending?

I'd like to re-fetch as often as possible without having multiple pending requests.

**Comment by sergiodxa** [comment]
Based on the code, what SWR does when you are using the refreshInterval feature is basically call the revalidate function it returns every X amount of time (C being what you configured), and the revalidate function has a way to deduce requests, that mean if the previous request hasn’t finished it should ensure a race condition doesn’t affect you ensuring the results second one is used instead to update the data instead of the old first one.

You can read more in the PR where this was added https://github.com/zeit/swr/pull/173

**Comment by pacocoursey** [comment]
Thanks @sergiodxa !

**Comment by shuding** [comment]
@anabeatrizzz Since SWR v1, you have to use `mutate()` instead of `revalidate()`, check https://swr.vercel.app/blog/swr-v1#change-revalidate-to-mutate.
