### ISSUE TITLE
[discussion] How swr + graphql-request compare to something like Apollo

### ISSUE THREAD

**Issue by bartol** [zeit/swr#26]
`graphql-request` is great graphql client for simple usage but lack of cache is preventing me from using it more. `swr` has nice hooks API and cache. 
How can these 2 libraries compare to something like React Apollo which is quite heavy for small web apps?

**Comment by sergiodxa** [comment]
I think Apollo cache is more powerful since it will detect your resources and if you fetch a resource A with the keys X and Y and later your fetch the key Z it should merge them.

SWR will cache based on the ID you pass it and overwrite the old one, so you could use your query as an ID but then you will have two cached items, A with X and Y and A with Z, if you later need your resource with the three keys and run a new query it will fetch it again since the query is different.

**Comment by bartol** [comment]
@sergiodxa Thanks for explanation!
