### ISSUE TITLE
Documentation mistake or incomprehension on my side

### ISSUE THREAD

**Issue by bbenezech** [zeit/swr#262]
I don't get the `so we don’t need to revalidate again` part from the documentation.
The second `mutate` does trigger a revalidation since we don't pass `false`.

From the documentation: 

But many POST APIs will just return the updated data directly, **so we don’t need to revalidate again.**
Here’s an example showing the “local mutate - request - update” usage:

```typescript
mutate('/api/user', newUser, false)      // use `false` to mutate without revalidation
mutate('/api/user', updateUser(newUser)) // `updateUser` is a Promise of the request,
                                         // which returns the updated document
```

I

**Comment by quietshu** [comment]
Hi @bbenezech , you are 100% correct here. The documentation is unclear about whether a revalidation will happen or not. 

We did some trick there: if it's a promise (async), we disable revalidation by default (because it probably returns the data directly and we don't need to revalidate again). Otherwise it's enabled by default. 

And now I realized this option was poorly designed. The ideal interface should be:

```js
mutate(key, dataOrRequest, shouldRevalidate = true)
```

We will improve it in #134 with the new API.
