### ISSUE TITLE
SWRConfig fetcher prop doesn't exist/work

### ISSUE THREAD

**Issue by davidalekna** [zeit/swr#285]
Hi, I'm trying to configure SWRConfig to use "global" fetch function in all hooks but it doesn't seem to work. Also [config interface](https://github.com/zeit/swr/blob/master/src/config.ts#L55) doesn't have a value called fetcher, like it's shown in the [docs](https://github.com/zeit/swr#global-configuration)

[codesandbox](https://codesandbox.io/s/jovial-babbage-wougg)

**Comment by cristianbgp** [comment]
I don't know about why the config interface doesn't have a value called fetcher, but in your example on [codesandbox](https://codesandbox.io/s/jovial-babbage-wougg) you are using `SWRConfig` wrong, since SWRConfig is a [Context.Provider](https://reactjs.org/docs/context.html), the prop that you should pass should be `value` not `values`

```jsx
<SWRConfig
  value={{
    fetcher: apiFetcher
  }}
>
  <SomeComponent />
</SWRConfig>
```

**Comment by sergiodxa** [comment]
@davidalekna @cristianbgp https://github.com/zeit/swr/blob/master/src/types.ts#L18 there is the fetcher in the config interface, https://github.com/zeit/swr/blob/master/src/config.ts#L55 that is the default config

**Comment by davidalekna** [comment]
@cristianbgp damn how did I miss that `values` vs `value` 😅

thanks for clarification guys!
