### ISSUE TITLE
missing revalidate in documentation

### ISSUE THREAD

**Issue by ilgianfra** [zeit/swr#298]
I am using `revalidate` as value returning from useSWR but I don't find it in the doc.

Also here there is an example of revalidate: https://github.com/zeit/swr/blob/master/examples/refetch-interval/pages/index.js

It could be useful adding that to the README

**Comment by sergiodxa** [comment]
Revalidate is going to be deprecated, mutate does the same if you don't pass any argument.

**Comment by enzoferey** [comment]
I wonder why this decision was made at an API surface level ? Calling `mutate()` seems to me like a hidden gem that would hard to discover by somebody that doesn't know the library and aliasing the call via `revalidate` is cheap to maintain I believe 🤔  

What were your thoughts around it @sergiodxa @shuding ?

**Comment by huozhi** [comment]
@enzoferey I feel the reason can be `mutate` is more flexible than `revalidate` that you can pass down any data for updating purpose or just revalidate the state. the functionality of `revalidate` can be replaced by `mutate` so that in new doc site swr didn't document `revalidate` API in the return values, can checkout https://swr.vercel.app/docs/mutation#revalidate
