### ISSUE TITLE
If the data is very large, the network request is very slow, can i use this plugin

### ISSUE THREAD

**Issue by wanliyunyan** [zeit/swr#333]
I'm worried that more and more requests are pending status, will this be a problem?

**Comment by shuding** [comment]
You can use this lib for sure, and that's also the purpose of this lib :+1: 
It doesn't matter what's the data size, because you are still using the same `fetch` under the hood. What can make a difference is behaviors like "focus revalidate", and you can turn them off if that becomes a problem (check [options](https://github.com/zeit/swr#options)). But of course it loses some real-time ablity.

The advantage of this lib under a slow network is, it caches and renders the data ASAP. You can check the Fast Navigation demo: https://swr.now.sh/#fast-navigation.
