### ISSUE TITLE
Direct writes to cache are possible, but are they intended?

### ISSUE THREAD

**Issue by ChrisLincoln** [zeit/swr#377]
Are the methods on the Cache class intended for public consumption?  I plan on having a CQRS data flow where the results of commands eventually trickle back to the client in the form of a websocket event.  It would be kind of cool to use cache.set() to pre-load the cache with data for which the client has not yet queried--creating a sort of pre-fetch behavior.

**Comment by sergiodxa** [comment]
The cache is exposed in case you want to build some integration like [swr-sync-storage](https://github.com/sergiodxa/swr-sync-storage), in your case I think using `mutate` will be enough, since it's similar to `cache.set` except it supports more feature like passing a promise and waiting for it to finish or passing a function and calling it.

**Comment by ChrisLincoln** [comment]
Awesome. I overlooked mutate as a stand-alone function. I thought it was dependent on existing as a member of the useSWR return tuple.
