### ISSUE TITLE
when component mounted , it had send many request, and how can i fix this problem

### ISSUE THREAD

**Issue by webKity** [zeit/swr#397]
when component mounted , it had send many request, this is my code: 
```
import React, { Suspense } from 'react';
import fetch from 'unfetch';
import useSWR from 'swr';

import { Card } from '../../../common';
import { Loading } from '../../../frame';

const fetcher = (url: string) => fetch(url).then(r => r.json());

const Users = () => {
  const { data: users, error } = useSWR(
    `/proxy/tribe/user/recommend?bk_time=${new Date().getTime()}`,
    fetcher,
    { suspense: true }
  );
  return (
    <Card title="Recommen">
      <div className="bitkan-ksite-recommenduser">
        { JSON.stringify(users) }
      </div>
    </Card>
  );
}
export default () => {
  return (
    <Suspense fallback={ <Loading></Loading> }>
      <Users></Users>
    </Suspense>
  );
}
```
is there someone can help me, thanks

**Comment by sergiodxa** [comment]
```
`/proxy/tribe/user/recommend?bk_time=${new Date().getTime()}`
```
The problem is there, combined with suspense every time you start rendering `Users` it will create a new date object and trigger a new request, then it will suspend until it has data, once the data is already cached it will unsuspend, but since the render will run again it will create a new data, suspending again and repeating this infinitely.

What you can do, is to store the date in another place, e.g. in a state or ref.

```js
const date = React.useRef(new Date().getTime())
const { data: users, error } = useSWR(
  `/proxy/tribe/user/recommend?bk_time=${date.current}`,
  fetcher,
  { suspense: true }
);
```

Or using state

 ```js
const [date, setData] = React.useState(new Date().getTime())
const { data: users, error } = useSWR(
  `/proxy/tribe/user/recommend?bk_time=${date}`,
  fetcher,
  { suspense: true }
);
```

The state option is better if you want to update it and cause a re-render.

Another options, is to create the date in the parent component and pass it as prop, this way the parent will generate the date only one time.

A last option, is to create the date object outside the React component, this will create it only one time for your whole app tho, so it will not be update until the user reload the page and you will have no way to update it, if you don't need it to be update this is probably the best solution.

**Comment by webKity** [comment]
thank you
