### ISSUE TITLE
how to use post method and pass params in swr?

### ISSUE THREAD

**Issue by nai6514531** [zeit/swr#93]

**Comment by monman2l** [comment]
const fetcher = params => url => post(url, params)
const { data, error } = useSWR('/api/user', fetcher({key: val}))

This way?

**Comment by sergiodxa** [comment]
SWR is more intended to get data, not update it, usually you have another function to update and after it you will run mutate to update the cache and trigger a revalidation (SWR will fetch it again)

**Comment by sergiodxa** [comment]
This example https://github.com/zeit/swr/tree/master/examples/optimistic-ui does something similar, update and then revalidate

**Comment by quietshu** [comment]
```js
function App() {
  const { data } = useSWR('/api/data', fetch) // <--------------GET

  return <>
    {data}
    <button onClick={() => {
      fetch('/api/data', { method: 'POST', body: ... })  // <---POST
    }}>update data</button>
  </>
}
```

You can just use `fetch` for POST requests. I don't see the benefit of allowing POST in SWR.  
And most importantly, most of the great features will be gone with POST (because it's not a "pure" action like GET, which is perfect for fetch-as-you-render):
- stale-while-revalidate (SWR)
- focus revalidate / polling
- automatically request deduplication
- caching
- ...

But speaking of revalidation/mutation, it's still a thing for allowing POST together with SWR. Currently we need to do this:

```js
mutate('/api/data', newData, false) // local mutate without revalidation
await sendPost('/api/data', newData) // POST request
trigger('/api/data') // revalidate
```

Maybe we can simplify it to something like:

```js
mutate('/api/data', newData, sendPost)
```

which will do the exact same thing as above.

**Comment by nicolasschabram** [comment]
Maybe it'd be worth checking out `react-query`'s [useMutation()](https://github.com/tannerlinsley/react-query#usemutation) hook for reference as well.

**Comment by iammarkps** [comment]
I have a use case with firebase onCall function(which it's method is POST). Because it supports authentication by default, I have to use this workaround.

```
import firebase from '../lib/firebase'

export const fetchSubmissionData = async (id: string) => {
  const getSubmission = firebase
    .app()
    .functions('asia-east2')
    .httpsCallable('getDetailedSubmissionData')

  return await getSubmission({ submission_id: id })
}
```
Then I can use
```
 const { data } = useSWR(`${id}`, fetchSubmissionData)
```

My function is onCall because it needs to verify user before sending back data.

Any idea on improving this? @quietshu

**Comment by quietshu** [comment]
@iammarkps can you show me a POST example you have without using SWR?

**Comment by iammarkps** [comment]
I always use it that way. But I'm just curious that, can I have only 1 global function to use firebase callable function?

Now I have to implement 3 different functions with same logic.

https://github.com/programming-in-th/programming.in.th/blob/master/src/utils/fetcher.ts

Because firebase callable function receives 2 args, not 1 like normal GET request(Just url of API).
Can SWR pass 2 arguments to functions?

PS.Pardon my bad english

**Comment by iammarkps** [comment]
I've used to do this when I was using redux (It's POST method).

https://github.com/programming-in-th/programming.in.th/blob/83ff9a23648e9ece55f8abeb555292da28908dac/src/redux/actions/submission.ts#L24

and this for normal data fetching (Still POST method)

https://github.com/programming-in-th/programming.in.th/blob/83ff9a23648e9ece55f8abeb555292da28908dac/src/redux/actions/task.ts#L34

But now I've converted it to normal http GET not firebase callable anymore.

https://github.com/programming-in-th/cloud_functions/blob/master/functions/src/tasks.ts#L4

So it works perfectly with SWR. 

But I can't convert [this](https://github.com/programming-in-th/cloud_functions/blob/master/functions/src/submissions.ts#L127) to http GET, because I have to check user right to access the code in line 187. So I need to depend on firebase request context. @quietshu

**Comment by iammarkps** [comment]
I want to do this

```

export const fetchFromFirebase = async (type: string, param?: Object) => {
    const get = firebase
    .app()
    .functions('asia-east2')
    .httpsCallable(type)

  return await get(param)
}

```

**Comment by quietshu** [comment]
@iammarkps thanks for elaborating! 👍

Now I can understand your use case, it makes perfect sense. 

> Can SWR pass 2 arguments to functions?

And yes! This feature will solve the problem: https://github.com/zeit/swr/pull/98

We just shipped it to `swr@0.1.9` and you can use it but the documentation is not yet updated. Ideally your code will be:
```js
useSWR([type, param], fetchFromFirebase)
```

But keep in mind it compares arguments shallowly, so keep in mind to memorize the object:
```js
const param = useMemo(() => ({ submission_id: id }), [id])
useSWR(['getDetailedSubmissionData', param], fetchFromFirebase)
```

**Comment by iammarkps** [comment]
@quietshu Thank you! I've just improved it with your suggestion in [this commit](https://github.com/programming-in-th/programming.in.th/commit/19eab582428eb503f9f59667340db0fb443cfef3)

**Comment by quietshu** [comment]
@iammarkps looks great!

**Comment by pedronauck** [comment]
So, this should be work in the newest version:

```
const { data: user } = useSWR('/api/user')
const params = useMemo(() => {
  return { username: user && user.username }
}, [user])

const profile = useSWR(() => ['/api/profile', params])
```

Because I'm trying this and I'm getting an infinite loop always 😕

**Comment by quietshu** [comment]
@pedronauck oh that's because you're using a function which returns an array here:
```js
const profile = useSWR(() => ['/api/profile', params])
```

This case is not yet covered (thanks for reporting!), for now you can just use an array:
```js
const profile = useSWR(['/api/profile', params])
```

**Comment by DeepakKapiswe** [comment]
I Used like this and it worked for me, please let me know If I’m missing something 
```
let url = 'some url here';

export default function ComponentName  (props) {
  const fetcher = (...args) => fetch(url, {
    method: 'post',
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(props.payload)
  }).then(res => res.json())

  const { data, error} = useSWR(url, fetcher, { suspense: true });
```

**Comment by theweiweiway** [comment]
Hi! Great library, I had a quick question:

```
const profile = useSWR(() => ['/api/profile', params])
```
Right now, it's fetching whenever params changes. Is there a way for me to programatically make it fetch with new params when a specific variable changes?

Thanks

**Comment by sergiodxa** [comment]
You need to pass every attribute inside `params` as different elements of the array.

**Comment by yufengwang** [comment]
mark

**Comment by Panjo9** [comment]
well, this works for me: 
`const fetcher = async (api, data) => {
  try {
    const response = await axios.post(api, data);
    return response.data;
  } catch (error) {
    console.error('Error', error);
  }
};

export default function useCustomHook({ data }) {
  const {
    data: dataHook ,
    error,
    isLoading,
  } = useFetchSWR(['url', { data  }], ([api, data]) => fetcher(url, data));

  return { dataHook } ;
}`
